### ISSUE TITLE
didnt understand cloneNode()

### ISSUE THREAD

**Issue by manali8785** [pvtech/DOM-Scripting-2#1]
var clonedNode=document.cloneNode(document.body.lastChild);
        console.log(clonedNode);

why clonedNode returns #document element instead of lastchild.In my case I have <script> element as lastchild

**Comment by pvtech** [comment]
Your syntax is incorrect. (Refer to this)[https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode]

The correct syntax for what you are trying to achieve:
``` var duplicate_div = document.body.lastChild.cloneNode(true); ```

The true is for deep clone (clone all the child nodes that exist within the node). 

Be careful with the event syntax though. You may land up selecting a text node as the last child.
